# Generated by Django 5.1.6 on 2025-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
