# Generated by Django 5.1.6 on 2025-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0002_product_isvisible'),
    ]

    operations = [
        migrations.CreateModel(
            name='picfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('furl', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
